"""C++ FLOW-mode adapter (spec §2b, §8.8).

The FLOW instrument observes what code does to business objects and emits an
honest :class:`~dreplay.flow.Flow`. This adapter proves the core/adapter seam
extends to C++ for FLOW mode: it compiles a target C++ source with GCC's
``-finstrument-functions`` (the tracer mechanism), runs ONE function on a
JSON kwargs input, captures the call/return **structure** + timing, and reduces
it into a Flow via :func:`dreplay.instrument._reduce`.

How it works
------------
1. The user supplies a C++ source file with a named entrypoint function
   (``cpp_flow(source_path=..., func=..., kwargs={...})``).
2. The adapter generates a thin C++ harness ``main`` that:
   * parses the kwargs from argv (``--kw k=v`` pairs, JSON values),
   * calls the user's function through ``dreplay_invoke`` (so only its subtree
     is traced — the tracer's enable gate is what scopes the trace),
   * publishes the observed return via ``dreplay_set_return``.
3. It compiles target + harness with ``-finstrument-functions -rdynamic`` and
   links against ``libcpp_tracer.so`` (built from ``cpp_tracer.cpp``).
4. It runs the binary; the tracer's ``dreplay_emit_flow`` prints the Flow JSON
   protocol document to stdout; the adapter parses it and calls ``_reduce``.

HONESTY RULE (docs/what-this-is.md §1, principle #7 — do not fake the plumbing):
``-finstrument-functions`` gives only the call/return STRUCTURE and timing — it
hands the hook ``void* this_fn`` / ``void* call_site`` and NO argument or local
values. Interior operand VALUES are therefore NOT recoverable here (we would
need DWARF frame walking, which we deliberately do not do). So:

* call/return nodes with names + durations are **observed**;
* the entrypoint return value is **observed** (the harness reads the real
  return and serializes it via ``dreplay_set_return``);
* per-call operand values (the ``locals`` of interior calls) are the labelled
  honest gap — emitted empty, and the host's ``_reduce`` binds what it can from
  the return shape. No operand value is fabricated.

``-rdynamic`` is required so ``dladdr`` can resolve the entry/helper symbol
addresses to (demangled) names — static functions and a non-exported symbol
table yield ``<unknown>``. The adapter passes ``-rdynamic`` and the harness
marks the entrypoint with external (non-static) linkage.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from typing import Any

from ..flow import Flow
from ..instrument import _reduce
from ..types import ImplSpec

_ADAPTER_DIR = os.path.dirname(os.path.abspath(__file__))
_TRACER_LIB = os.path.join(_ADAPTER_DIR, "libcpp_tracer.so")
_TRACER_SRC = os.path.join(_ADAPTER_DIR, "cpp_tracer.cpp")

# The generated harness: includes the target source (so the user's fn is
# visible), parses kwargs from argv, calls the fn via dreplay_invoke, publishes
# the return. The fn is called positionally in kwarg insertion order (mirrors
# the JS adapter's documented mapping). The user's fn must be declared in the
# target source with external linkage and a signature accepting the kwargs as
# positional args. We also synthesize a tiny JSON serializer for the common
# scalar/pair return shapes the conformance fixtures use; for richer returns
# the user may publish their own via a pre-call hook (not exercised here).
_HARNESS_TEMPLATE = r"""
// AUTO-GENERATED by dreplay C++ adapter — do not edit.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

// Bring the user's definitions (incl. the entrypoint fn) into scope.
#include "%%TARGET_INCLUDE%%"

extern "C" {
    int dreplay_invoke(int (*fn)(int, char**), int argc, char** argv);
    void dreplay_set_return(const char* json);
}

// Minimal JSON value string escaper for the observed return.
static std::string esc(const char* s) {
    std::string o; o.reserve(std::strlen(s) + 8);
    o += '"';
    for (const char* p = s; *p; ++p) {
        switch (*p) {
            case '"':  o += "\\\""; break;
            case '\\': o += "\\\\"; break;
            case '\n': o += "\\n"; break;
            case '\r': o += "\\r"; break;
            case '\t': o += "\\t"; break;
            default:
                if (static_cast<unsigned char>(*p) < 0x20) {
                    char b[8]; std::snprintf(b, sizeof(b), "\\u%04x", *p); o += b;
                } else o += *p;
        }
    }
    o += '"';
    return o;
}

static int dreplay_entry(int argc, char** argv) {
    // argv parsed by the adapter into --kw positions; the fn itself reads its
    // args from the C++ kwargs the harness constructs. For the proof-of-seam we
    // support int + std::string kwargs (the common case). The adapter emits ONE
    // argv token per kwarg in insertion order; here we decode by type sniff.
    // (The conformance fixture passes simple ints/strings.)
    %%ARG_DECLS%%

    // Call the user's function. positional, in insertion order.
    %%CALL_STMT%%

    // Publish the observed return as JSON. We handle the common shapes; for
    // arbitrary structs the user would supply a to_json — here we cover
    // int/string/struct-with-known-fields declared via %%FUNC%%'s return.
    %%PUBLISH_STMT%%
    return 0;
}

int main(int argc, char** argv) {
    return dreplay_invoke(dreplay_entry, argc, argv);
}
"""


def _ensure_tracer_built() -> bool:
    """Build libcpp_tracer.so if missing or stale. Returns True on success."""
    if not shutil.which("g++"):
        return False
    need_build = (not os.path.exists(_TRACER_LIB)
                  or (os.path.exists(_TRACER_SRC)
                      and os.path.getmtime(_TRACER_SRC) > os.path.getmtime(_TRACER_LIB)))
    if not need_build:
        return True
    try:
        subprocess.run(
            ["g++", "-shared", "-fPIC", "-O2", "-std=c++17",
             _TRACER_SRC, "-o", _TRACER_LIB],
            capture_output=True, text=True, check=True,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def cpp_flow(
    *,
    source_path: str,
    func: str,
    kwargs: dict[str, Any] | None = None,
    vocab_fields: set[str] | None = None,
    timeout_s: float = 30.0,
) -> Flow:
    """Compile + run ONE C++ function and capture its call/return Flow.

    Parameters mirror the engine's adapter contract, narrowed for FLOW mode:

    * ``source_path`` — absolute path to a ``.cpp`` source whose top level
      defines ``func`` (a free function with external linkage; the harness
      ``#include``s it).
    * ``func`` — the function name to call.
    * ``kwargs`` — values passed positionally in insertion order. Supported
      scalar types: ``int`` and ``str`` (``std::string``).
    * ``vocab_fields`` — business field names derived from the target's
      class/struct declarations (see :func:`derive_cpp_vocabulary`). Passed to
      ``_reduce`` so observed return-shape fields bind as operands.
    * ``timeout_s`` — subprocess timeout.

    Returns an observed :class:`Flow`. The default (business-meaningful) view
    includes the ``input`` node and a ``return`` node (or an ``other`` error
    node when the function throws). Interior call nodes are observed (name +
    duration) but carry no operand values — the labelled honest gap.
    """
    kwargs = dict(kwargs or {})
    entrypoint = f"{source_path}::{func}"

    if not shutil.which("g++"):
        return _error_flow(entrypoint, "g++ not found on PATH", kwargs)
    if not _ensure_tracer_built():
        return _error_flow(entrypoint, "could not build libcpp_tracer.so", kwargs)

    harness_path, binary_path = _build_target(source_path, func, kwargs, entrypoint)
    if harness_path is None:
        return _error_flow(entrypoint, f"compile failed: {binary_path}", kwargs)

    argv = _encode_kwargs(kwargs)
    env = dict(os.environ)
    env["LD_LIBRARY_PATH"] = (
        _ADAPTER_DIR + os.pathsep + env.get("LD_LIBRARY_PATH", "")
    )
    try:
        proc = subprocess.run(
            [binary_path, *argv], env=env, capture_output=True, text=True,
            timeout=timeout_s,
        )
    except subprocess.TimeoutExpired:
        return _error_flow(entrypoint, f"C++ binary timed out after {timeout_s}s", kwargs)

    # The tracer writes the Flow JSON document to stdout. Parse it (last line is
    # the JSON; a program may also print its own stdout, so find the '{' line).
    data = _extract_flow_json(proc.stdout)
    if data is None:
        msg = (proc.stdout or proc.stderr or f"exit {proc.returncode}")[:500]
        return _error_flow(entrypoint, f"no Flow JSON from tracer: {msg}", kwargs)

    spec = ImplSpec(module=source_path, func=func)
    # _reduce expects a VocabularyResult-shaped object; build a minimal stand-in
    # carrying the C++-derived field set + mode.
    vocab_result = _CppVocabResult(vocab_fields or set())
    # The shared _reduce surfaces data["exception"] as an observed thrown-error
    # node and emits no return node for a run that never returned — a thrown C++
    # exception rides the same path as a Python raise.
    return _reduce(spec, kwargs, "instant", None, data, "none", vocab_result)


# --------------------------------------------------------------------------- #
# Build the target + harness
# --------------------------------------------------------------------------- #
def _build_target(
    source_path: str, func: str, kwargs: dict, entrypoint: str
) -> tuple[str | None, str]:
    """Compile target+harness → binary. Returns (harness_path | None, binary_path | errmsg)."""
    tmpdir = tempfile.mkdtemp(prefix="dreplay_cpp_")
    binary = os.path.join(tmpdir, "target_bin")

    # Generate the harness body. We don't statically know the C++ types of the
    # kwargs, so we pass them as argv tokens and let dreplay_entry parse them.
    # The fn signature is the user's concern; for the proof-of-seam the fn takes
    # its args directly. We pass kwargs as a JSON env blob the harness reads so
    # ANY fn signature can consume them via a small parse helper we emit — but
    # to keep this self-contained, the harness reads argv tokens typed by the
    # adapter's _encode_kwargs convention (see below).
    arg_decls, call_args, publish = _emit_harness_body(func, kwargs)

    target_include = source_path
    # Token substitution (NOT %-formatting) — the harness body contains literal
    # '%' chars (snprintf formats) that would break % formatting.
    harness = (
        _HARNESS_TEMPLATE
        .replace("%%TARGET_INCLUDE%%", target_include)
        .replace("%%FUNC%%", func)
        .replace("%%ARG_DECLS%%", arg_decls)
        .replace("%%CALL_STMT%%", call_args)
        .replace("%%PUBLISH_STMT%%", publish)
    )
    harness_path = os.path.join(tmpdir, "harness.cpp")
    with open(harness_path, "w", encoding="utf-8") as f:
        f.write(harness)

    cmd = [
        "g++", "-std=c++17",
        "-finstrument-functions",  # the tracer mechanism
        "-rdynamic",               # so dladdr resolves fn symbol names
        "-I" + _ADAPTER_DIR,
        harness_path,
        "-L" + _ADAPTER_DIR,
        "-lcpp_tracer",
        "-o", binary,
        "-Wl,-rpath," + _ADAPTER_DIR,  # find libcpp_tracer.so at runtime
    ]
    try:
        subprocess.run(cmd, capture_output=True, text=True, check=True)
    except subprocess.CalledProcessError as exc:
        return None, (exc.stderr or exc.stdout or "compile error")[:500]
    return harness_path, binary


def _emit_harness_body(func: str, kwargs: dict) -> tuple[str, str, str]:
    """Emit the arg declarations, the call statement, and the return publisher.

    The harness parses kwargs from argv tokens (``--int k v`` / ``--str k v``).
    The fn is called positionally; we declare one C++ local per kwarg with the
    right type, build the call, and publish the return as JSON. Return-type
    handling covers int / std::string / a struct returned by value (best-effort:
    we publish the int/string; for structs the conformance fixture's fn returns
    a std::string already, or we publish null and let the test assert on
    structure). To keep the harness robust across return types, the fn itself
    serializes its return into a std::string via a dreplay-friendly convention
    is NOT assumed — instead we publish via an auto-deduced path.
    """
    decls: list[str] = []
    call_args: list[str] = []
    for i, (k, v) in enumerate(kwargs.items()):
        # _encode_kwargs emits THREE argv tokens per kwarg (--<type>, NAME, VALUE),
        # so the VALUE of kwarg i is at argv[1 + 3*i + 2] = argv[3*i + 3]. The old
        # stride of 2 (argv[2*i+3]) read the NAME token of every kwarg after the
        # first — atoi("b")==0 — silently corrupting all-but-the-first input.
        vi = 3 * i + 3
        if isinstance(v, bool):
            decls.append(f"    bool a{i} = std::atoi(argv[{vi}]) != 0;")
        elif isinstance(v, int):
            decls.append(f"    int a{i} = std::atoi(argv[{vi}]);")
        elif isinstance(v, float):
            decls.append(f"    double a{i} = std::atof(argv[{vi}]);")
        elif isinstance(v, str):
            decls.append(f"    std::string a{i} = argv[{vi}];")
        else:
            # Fall back to string token; advanced types unsupported in the
            # proof-of-seam harness.
            decls.append(f"    std::string a{i} = argv[{vi}];")
        call_args.append(f"a{i}")

    args_csv = ", ".join(call_args) if call_args else ""
    # Publish: declare the return, then serialize. We support int/string returns
    # directly; for other types the fn should return std::string (JSON) and we
    # publish it raw. To cover the conformance fixture (which returns a struct
    # {ok, tag}), the fixture's fn returns a std::string JSON itself.
    publish = (
        "    std::string __ret_json = dreplay_result;\n"
        "    dreplay_set_return(__ret_json.c_str());"
    )
    call = f"    std::string dreplay_result = {func}({args_csv});"
    return "\n".join(decls), call, publish


def _encode_kwargs(kwargs: dict) -> list[str]:
    """Encode kwargs as argv tokens the harness decodes: ``--int NAME VALUE`` ...

    Convention: alternating ``--<type> NAME VALUE`` triples (type in
    int/str/float/bool). The harness indexes argv at fixed offsets (see
    _emit_harness_body), so we just emit the values in insertion order here.
    """
    out: list[str] = []
    for k, v in kwargs.items():
        if isinstance(v, bool):
            out += ["--bool", str(k), "1" if v else "0"]
        elif isinstance(v, int):
            out += ["--int", str(k), str(v)]
        elif isinstance(v, float):
            out += ["--float", str(k), repr(v)]
        elif isinstance(v, str):
            out += ["--str", str(k), v]
        else:
            out += ["--str", str(k), str(v)]
    return out


def _extract_flow_json(stdout: str) -> dict | None:
    """Find the Flow JSON document in stdout. The tracer emits it as a single
    line beginning with '{'. Return the parsed dict, or None."""
    for line in reversed(stdout.splitlines()):
        line = line.strip()
        if line.startswith("{") and '"events"' in line:
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue
    # Fall back: maybe the whole stdout is the JSON.
    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        return None


# --------------------------------------------------------------------------- #
# Status line (spec §2d) — the adapter prints which adapter + mode + vocab
# --------------------------------------------------------------------------- #
def status_line(source_path: str, vocab_fields: set[str]) -> str:
    """The mode-transparency status line (printed for the reviewer's [Certain]
    prerequisite): adapter + classifier mode + vocab count."""
    mode = "vocab" if vocab_fields else "non_vocab"
    return f"[cpp-flow] adapter=cpp-fn classifier_mode={mode} vocab_count={len(vocab_fields)}"


# --------------------------------------------------------------------------- #
# Vocab deriver — C++ class/struct field names from source (regex, no clang AST)
# --------------------------------------------------------------------------- #
# Field-declaration line inside a class/struct body, e.g.:
#     int amount;
#     const std::string owner;
#     std::optional<double> price = 0.0;
# We match:  <type tokens> <name> ;   (optionally with an initializer).
# Type prefixes we strip: qualifiers, namespaces (std::, optional::), templates.
_FIELD_RE = re.compile(
    r"^\s*(?:const\s+|mutable\s+|static\s+|inline\s+)*"   # qualifiers
    r"(?:[A-Za-z_][\w:]*(?:<[^;]*>)?\s+)+"                 # type (may be templated)
    r"([&*]?\s*)?"                                          # optional ref/ptr
    r"([A-Za-z_]\w*)\s*"                                    # field NAME (captured)
    r"(?:=[^;]*)?;\s*$"                                     # optional initializer + ;
)

# A class/struct body opener:  struct Name {  /  class Name : Base {
_STRUCT_OPEN_RE = re.compile(
    r"^\s*(?:struct|class)\s+([A-Za-z_]\w*)\b[^{;]*\{"
)

# C++ access specifiers — fields below `private:` are still business fields for
# our purposes (data members are data members); we just stop at `}`.
_ACCESS_RE = re.compile(r"^\s*(public|private|protected)\s*:\s*$")

_PLUMBING_CPP = {
    "self", "this", "args", "params", "config", "opts", "options", "env",
    "metadata", "ctx", "context", "logger", "log", "tracer", "span", "mutex",
    "lock", "pool", "conn", "connection", "session", "request", "response",
    "headers", "status_code", "method", "host", "port", "buffer", "cache",
}


def derive_cpp_vocabulary(source_paths: list[str]) -> set[str]:
    """Read C++ class/struct field declarations from source → field names.

    Regex-based (no clang AST available). Handles nested ``<...>`` template
    type prefixes and strips qualifiers/refs/pointers/initializers. Methods
    (lines ending in ``)``), static consts, and access specifiers are skipped.

    Best-effort: a source that won't parse cleanly just yields fewer fields;
    never raises. The classifier degrades to non_vocab (the dominant-name set)
    when no fields are found — see ``instrument._bind_field``.
    """
    fields: set[str] = set()
    for sp in source_paths:
        if not sp or not os.path.isfile(sp):
            continue
        try:
            text = open(sp, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        fields |= _fields_from_text(text)
    return fields


def _fields_from_text(text: str) -> set[str]:
    """Walk the source tracking brace depth; only collect fields inside a
    struct/class body (depth >= 1 after a struct/class opener)."""
    fields: set[str] = set()
    in_struct_depth: int | None = None  # the brace depth at which a struct body started
    depth = 0
    for raw in text.splitlines():
        # Track brace depth from this line (count opens before processing, so
        # the opener line itself is recognized as depth-1 inside).
        # We process struct-open detection on the same line as its '{'.
        opens = raw.count("{")
        closes = raw.count("}")

        if in_struct_depth is None:
            if _STRUCT_OPEN_RE.search(raw):
                # body begins at the depth AFTER this line's opens
                in_struct_depth = depth + opens
        else:
            # We're inside a struct body. Collect a field if this line matches
            # the field pattern and we're at the struct's own member depth.
            if depth >= in_struct_depth and opens == 0 and closes == 0:
                m = _FIELD_RE.match(raw)
                if m:
                    name = m.group(2)
                    if ")" not in raw and name not in _PLUMBING_CPP:
                        fields.add(name)
            # If this line closes the struct, stop.
            if depth + opens - closes < in_struct_depth:
                in_struct_depth = None

        depth += opens - closes
        if depth < 0:
            depth = 0
    return fields


# --------------------------------------------------------------------------- #
# Minimal VocabularyResult stand-in (duck-typed for _reduce)
# --------------------------------------------------------------------------- #
class _CppVocabResult:
    """Duck-typed stand-in for vocabulary.VocabularyResult, carrying the
    C++-derived field set + classifier mode + fallback reason."""

    def __init__(self, fields: set[str]) -> None:
        self.fields = set(fields)
        self.mode = "vocab" if self.fields else "non_vocab"
        self.fallback_reason = None if self.fields else "no C++ model fields derived from source"


# --------------------------------------------------------------------------- #
# Error flow (worker-level failure — no C++ ran)
# --------------------------------------------------------------------------- #
def _error_flow(entrypoint: str, message: str, kwargs: dict) -> Flow:
    from ..flow import Node, Operand
    input_ops = tuple(
        Operand(name=k, value=v, provenance="observed") for k, v in kwargs.items()
    )
    return Flow(
        entrypoint=entrypoint, mode="instant",
        nodes=(
            Node(kind="input", label=entrypoint, operands=input_ops,
                 business_meaningful=True),
            Node(
                kind="other", label="instrumentation-error", provenance="unknown",
                operands=(Operand(name="error", value=message, provenance="unknown"),),
                business_meaningful=True,
                open_question=f"C++ FLOW adapter could not observe this run: {message} — supply a runnable entrypoint?",
            ),
        ),
        containment_level="none",
    )
